import React from 'react';
import { SignInView } from '@/components/sections/SignIn/SignIn';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Bad Trip | Sign In',
    description: 'Generated by create next app',
};

export default function SignIn() {
    return (
        <main>
            <SignInView />
        </main>
    );
}
