import React from 'react';
import type { Metadata } from 'next';
import { Document } from '@contentful/rich-text-types';

import { getContent } from '@/contentful/utils';
import { contentfulConstants } from '@/contentful/contentful-constants';
import { AboutUsView } from '@/components/sections/AboutUs/AboutUsView';
import { Navigation } from '@/components/common/Navigation/Navigation';

//--------------------------------------------------------

export const metadata: Metadata = {
    title: 'Bad Trip | About Us',
    description: 'Generated by create next app',
};

//--------------------------------------------------------

const spaceId = contentfulConstants.space.aboutUsSpace;
const contentId = contentfulConstants.content.aboutUsContent;

//--------------------------------------------------------

export default async function AboutUs() {
    const fetchedContent = await getContent(spaceId as string, contentId as string);
    return (
        <main>
            <Navigation />
            <AboutUsView content={fetchedContent?.aboutUsContent as Document} />
        </main>
    );
}

//--------------------------------------------------------
