import React from 'react';
import type { Metadata } from 'next';
import { Document } from '@contentful/rich-text-types';

import { getContent } from '@/contentful/utils';
import { contentfulConstants } from '@/contentful/contentful-constants';
import { ContactUsView } from '@/components/sections/ContactUs/ContactUsView';
import { Navigation } from '@/components/common/Navigation/Navigation';

//--------------------------------------------------------

export const metadata: Metadata = {
    title: 'Bad Trip | Contact',
    description: 'Generated by create next app',
};

//--------------------------------------------------------

const spaceId = contentfulConstants.space;
const contentId = contentfulConstants.content.contactUsContent;

//--------------------------------------------------------

export default async function AboutUs() {
    const fetchedContent = await getContent(spaceId as string, contentId as string);
    const { contactUsTitle, contactUsOrganizationData } = fetchedContent;
    return (
        <main>
            <Navigation />
            <ContactUsView
                title={contactUsTitle as Document}
                organizationData={contactUsOrganizationData as Document}
            />
        </main>
    );
}

//--------------------------------------------------------
