import type { Metadata } from 'next'
import Image from 'next/image'

export const metadata: Metadata = {
  title: 'Bad Trip | Sign up',
  description: 'Generated by create next app',
}

export const SignUp = () => {
  return (
    <main>
      
    </main>
  )
}
